<a href="https://colab.research.google.com/github/np03cs4a240162-alina/Worksheet1-alinamanandhar/blob/main/AI_worksheet_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy. Problem - 1: Array Creation:


In [ ]:
import numpy as np

# Task 1: Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

# Task 2: Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll-One Array (4x2):\n", ones_array)

# Task 3: Return a new array of given shape and type, filled with a fill value

filled_array = np.full((3, 3), fill_value=7, dtype=int)
print("\nFilled Array (3x3) with 7:\n", filled_array)

# Task 4: Return a new array of zeros with same shape and type as a given array
example_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
zeros_like_array = np.zeros_like(example_array)
print("\nZeros Like Example Array:\n", zeros_like_array)

# Task 5: Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(example_array)
print("\nOnes Like Example Array:\n", ones_like_array)

# Task 6: Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\nArray from List:\n", array_from_list)


Empty Array (2x2):
 [[2.39586137e-315 0.00000000e+000]
 [6.55572298e-310 6.55572319e-310]]

All-One Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array (3x3) with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Example Array:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Like Example Array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Array from List:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing

In [ ]:
import numpy as np

# Task 1: Create an array with values ranging from 10 to 49
array_10_49 = np.arange(10, 50)
print("Array from 10 to 49:\n", array_10_49)

# Task 2: Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print("\n3x3 Matrix from 0 to 8:\n", matrix_3x3)

# Task 3: Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# Task 4: Create a random array of size 30 and find the mean
random_array_30 = np.random.random(30)
mean_value = random_array_30.mean()
print("\nRandom Array of size 30:\n", random_array_30)
print("Mean of the array:", mean_value)

# Task 5: Create a 10x10 array with random values and find min & max
random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print("\n10x10 Random Array:\n", random_10x10)
print("Min value:", min_val)
print("Max value:", max_val)

# Task 6: Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1   # Indexing starts from 0
print("\nZero array with 5th element as 1:\n", zero_array)

# Task 7: Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)

# Task 8: Create a 2D array with 1 on border and 0 inside
# Example size: 5x5
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with border 1 and inside 0:\n", border_array)

# Task 9: Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
 [0.74621773 0.95015872 0.05569342 0.50269934 0.37808941 0.59157104
 0.00219    0.53329514 0.40538516 0.6743532  0.89319994 0.30441577
 0.3216158  0.31615579 0.43081269 0.10218858 0.09087118 0.03240806
 0.51983985 0.40466117 0.26262569 0.26327244 0.39515653 0.19194856
 0.45809406 0.05078816 0.21852996 0.35703431 0.04810337 0.24765437]
Mean of the array: 0.35830098154917883

10x10 Random Array:
 [[0.32847326 0.92289415 0.19905963 0.10547945 0.82483989 0.78695797
  0.11943264 0.87812831 0.27830695 0.71868025]
 [0.91074515 0.93644186 0.48545526 0.61326398 0.53816317 0.67982377
  0.81509034 0.85075246 0.9153506  0.13957859]
 [0.60809368 0.14256325 0.2029874  0.13316344 0.02998264 0.03250449
  0.44155078 0.9351

Problem - 3: Array Operations:


In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Task 1: Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# Task 2: Subtract the two arrays
sub_xy = x - y
print("\nSubtraction of x and y:\n", sub_xy)

# Task 3: Multiply the array with an integer (example: 3)
mul_x = x * 3
print("\nMultiplication of x by 3:\n", mul_x)

# Task 4: Square of each element
square_x = x ** 2
print("\nSquare of elements in x:\n", square_x)

# Task 5: Dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

# Task 6: Concatenate x and y along rows (axis=0) and v and w along columns
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.column_stack((v, w))  # same as np.concatenate((v[:,None], w[:,None]), axis=1)
print("\nConcatenate x and y along rows:\n", concat_xy_row)
print("Concatenate v and w along columns:\n", concat_vw_col)

# Task 7: Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = e
print("\nAttempt to concatenate x and v gives error:\n", concat_xv_error)
print("Explanation: x is 2x2 (2D) and v is 1D. Arrays must have the same number of dimensions along concatenation axis.")


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]

Square of elements in x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

Attempt to concatenate x and v gives error:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is 2x2 (2D) and v is 1D. Arrays must have the same number of dimensions along concatenation axis.


Problem 4: Matrix Operations

In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])

# Task 1: Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A^-1:\n", identity)
print("Is identity matrix? ", np.allclose(identity, np.eye(2)))  # np.allclose handles floating point precision

# Task 2: Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)
print("AB equals BA? ", np.array_equal(AB, BA))

# Task 3: Prove (AB)^T = B^T * A^T
AB_T = (np.dot(A, B)).T
B_T_A_T = np.dot(B.T, A.T)
print("\n(AB)^T:\n", AB_T)
print("B^T * A^T:\n", B_T_A_T)
print("Check equality: ", np.array_equal(AB_T, B_T_A_T))

# Task 4: Solve the system of linear equations using inverse method
# Equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Representing in matrix form: AX = B
coeff_matrix = np.array([[2, -3, 1],
                         [1, -1, 2],
                         [3, 1, -1]])
constant_matrix = np.array([-1, -3, 9])

# Solve using np.linalg.inv
X = np.dot(np.linalg.inv(coeff_matrix), constant_matrix)
print("\nSolution using inverse method:\n", X)

# Optional: Solve using np.linalg.solve (recommended)
X_solve = np.linalg.solve(coeff_matrix, constant_matrix)
print("Solution using np.linalg.solve:\n", X_solve)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is identity matrix?  True

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB equals BA?  False

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Check equality:  True

Solution using inverse method:
 [ 2.  1. -2.]
Solution using np.linalg.solve:
 [ 2.  1. -2.]


4.2.1

In [ ]:
import numpy as np
import time

# Size of the arrays/lists
N = 1_000_000

# Using Python Lists
list1 = list(range(N))
list2 = list(range(N))

start_time = time.time()

# Element-wise addition using list comprehension
list_sum = [list1[i] + list2[i] for i in range(N)]

end_time = time.time()
python_list_time = end_time - start_time
print("Time taken using Python lists:", python_list_time, "seconds")

# -------------------------------
# Using NumPy Arrays
# -------------------------------
array1 = np.arange(N)
array2 = np.arange(N)

start_time = time.time()

# Element-wise addition using NumPy
array_sum = array1 + array2

end_time = time.time()
numpy_array_time = end_time - start_time
print("Time taken using NumPy arrays:", numpy_array_time, "seconds")


Time taken using Python lists: 0.11799192428588867 seconds
Time taken using NumPy arrays: 0.00514531135559082 seconds


4.2.2

In [ ]:
import numpy as np
import time

# Size of the arrays/lists
N = 1_000_000

# Using Python Lists

list1 = list(range(N))
list2 = list(range(N))

start_time = time.time()

# Element-wise multiplication using list comprehension
list_product = [list1[i] * list2[i] for i in range(N)]

end_time = time.time()
python_list_time = end_time - start_time
print("Time taken using Python lists for multiplication:", python_list_time, "seconds")

# Using NumPy Arrays

array1 = np.arange(N)
array2 = np.arange(N)

start_time = time.time()

# Element-wise multiplication using NumPy
array_product = array1 * array2

end_time = time.time()
numpy_array_time = end_time - start_time
print("Time taken using NumPy arrays for multiplication:", numpy_array_time, "seconds")


Time taken using Python lists for multiplication: 0.19674468040466309 seconds
Time taken using NumPy arrays for multiplication: 0.008664846420288086 seconds


4.2.3 & 4.2.4

In [ ]:
import numpy as np
import time

# -------------------------------
# 3. Dot Product
# -------------------------------
N = 1_000_000

# Using Python Lists
list1 = list(range(N))
list2 = list(range(N))

start_time = time.time()
dot_product_list = sum([list1[i] * list2[i] for i in range(N)])
end_time = time.time()
print("Dot Product using Python lists:", dot_product_list)
print("Time taken using Python lists:", end_time - start_time, "seconds")

# Using NumPy Arrays
array1 = np.arange(N)
array2 = np.arange(N)

start_time = time.time()
dot_product_array = np.dot(array1, array2)
end_time = time.time()
print("Dot Product using NumPy arrays:", dot_product_array)
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")


# -------------------------------
# 4. Matrix Multiplication
# -------------------------------
size = 1000

# Using Python Lists
# Create matrices
matrix1 = [[i + j for j in range(size)] for i in range(size)]
matrix2 = [[i + j for j in range(size)] for i in range(size)]

start_time = time.time()
# Naive matrix multiplication
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
end_time = time.time()
print("\nMatrix multiplication using Python lists completed.")
print("Time taken using Python lists:", end_time - start_time, "seconds")

# Using NumPy Arrays
np_matrix1 = np.arange(size*size).reshape(size, size)
np_matrix2 = np.arange(size*size).reshape(size, size)

start_time = time.time()
np_result = np.dot(np_matrix1, np_matrix2)
end_time = time.time()
print("Matrix multiplication using NumPy arrays completed.")
print("Time taken using NumPy arrays:", end_time - start_time, "seconds")


Dot Product using Python lists: 333332833333500000
Time taken using Python lists: 0.15912485122680664 seconds
Dot Product using NumPy arrays: 333332833333500000
Time taken using NumPy arrays: 0.0022377967834472656 seconds

Matrix multiplication using Python lists completed.
Time taken using Python lists: 213.48598647117615 seconds
Matrix multiplication using NumPy arrays completed.
Time taken using NumPy arrays: 3.0354373455047607 seconds
